services:
  postgres:
    image: postgres:16
    container_name: fleetstat-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: fleetstat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  fleetstat:
    build: .
    container_name: fleetstat-api
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      - postgres

    ports:
      - "8000:8000"

volumes:
  postgres_data:
